from core.util.op import APPLYORBIT_OP, CALIBRATE_OP, TERR_CORR_OP, SPECKLE_FILTER_OP, THERM_NOISE_OP, TOPSAR_DEBURST_OP

# NO_ARG_ALLOWED_OPS = [APPLYORBIT_OP, CALIBRATE_OP, TERR_CORR_OP, SPECKLE_FILTER_OP, THERM_NOISE_OP, TOPSAR_DEBURST_OP]