read:
  type: 'dict'
  required: True
  schema:
    module:
      type: 'string'
      required: True
      allowed: ['snap', 'gdal', 'netcdf']
    bands:
      type: 'list'
      empty: False
      required: false
      schema:
        oneof:
          - type: 'integer'
            min: 1
          - type: 'string'
    stack_files:
      type: 'list'
      empty: False
      required: false
      minlength: 1
      schema:        
        type: 'string'        
        empty: False
    read_and_stack:
      type: 'boolean'
      required: false
      default: False    