stack:
  type: 'dict'
  required: true

  schema:
    bands_list:
      type: 'list'
      required: false
      empty: false
      oneof:
        - type: 'list'
          schema:
            oneof:
            - type: 'string'
              allowed: ['None']
            - type: 'list'
              empty: false
              schema:
                oneof:
                  - type: 'integer'
                    min: 1
                  - type: 'string'

#                  allowed: ['None']
#              type: 'integer'
#              min: 1
#        - type: 'list'
#          schema:
#            type: 'list'
#            empty: false
#            schema:
#              oneof:
#                - type: 'integer'
#                - type: 'string'
#                  allowed: ['None']
#              type: 'string'
#        - type: 'list'
#          schema:
#            type: 'string'
#            allowed: ['None']
    master_module:
      type: 'string'
      required: true
      allowed: ['gdal', 'snap']