path_const: &path_cons '^(?:[a-zA-Z]:[\/]|[\/])?(?:[^\/:*?"<>{}|]+[\/])*[^\/:*?"<>{}| ]*$'
ext_const: &ext_cons '^(?:[.][a-zA-Z0-9]+)?$'

write:
  type: 'dict'
  required: true
  schema:
    out_dir:
      type: 'string'
#      dependencies: [output_affix, output_prefix]
      regex: *path_cons
      required: true
    out_stem:
      type: 'string'
      required: true

    suffix:
      type: 'string'
    prefix:
      type: 'string'
    out_ext:
      type: 'string'
#      dependencies: [module]
      allowed: [ 'tif', 'dim']