path_const: &path_cons '^(?:[a-zA-Z]:[\/]|[\/])?(?:[^\/:*?"<>{}|]+[\/])*[^\/:*?"<>{}| ]*$'
ext_const: &ext_cons '^(?:[.][a-zA-Z0-9]+)?$'

write:
  type: 'dict'
  required: true
  xor_fields : ['out_path', 'out_dir,out_stem']
  schema:
    bands:
      type: 'list'
      schema:
        oneof:
        - type: 'integer'
          min: 1
        - type: 'string'
    out_path:
      type: 'string'
      regex: *path_cons
    out_dir:
      type: 'string'
#      dependencies: [output_affix, output_prefix]
      regex: *path_cons
    out_stem:
      type: 'string'
    suffix:
      type: 'string'
    prefix:
      type: 'string'
    out_ext:
      type: 'string'
#      dependencies: [module]
      allowed: [ 'tif', 'dim']