sort_patt: &parse_str_patt '([12]\d{3}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])T(?:0[0-9]|1[0-9]|2[0-3])(?:[0-5][0-9])(?:[0-5][0-9]))'
date_patt: &parse_date_patt '%Y%m%dT%H%M%S'

read_s2_1:
  input: '$ETRI_DATA/_sentinel_1_2/export/source/s2'
  operations : ['read']

  read:
    pattern: '*.dim'
    loader: 'snap'
    sort:
      reg_exp: *parse_str_patt
      date_format: *parse_date_patt

read_s2_2:
  input: '$ETRI_DATA/_sentinel_1_2/export/source/s2'
  operations : ['read']

  read:
    pattern: '*.dim'
    loader: 'snap'
    sort:
      func: '!{sort_by_name}'

stack_s2_1_2:
  input: ['{{read_s2_1}}', '{{read_s2_2}}']
  operations : ['stack']

  stack:
    axis: -1

read_s2_3:
  input: '$ETRI_DATA/_sentinel_1_2/export/source/s2'
  operations : ['read']

  read:
    pattern: '*.dim'
    loader: 'snap'
    sort:
      func: '!{sort_by_name}'

cal_1:
  input: ['{{read_s2_1}}']
  operations : ['atmos']
  atmos:
    config: '$PROJECT_PATH/config/atmos/defaults/S2A_MSI.txt'

preprocessing_s2_1:
  input: ['{{stack_s2_1_2}}', '{{cal_1}}', '{{read_s2_3}}']
  operations : ['stack', 'subset']

  stack:
    axis: -1

  subset:
    epsg: 4326
    bounds: [ 126.0, 38.2, 126.2, 38.0 ]

preprocessing_s2_2:
  input: '{{preprocessing_s2_1}}'
  operations : ['write']
  write:
    output_root: '$ETRI_DATA/_sentinel_1_2/export/calibrated/s2/'
    output_prefix: 's2_'
    saver: 'snap'

preprocessing_s2:
  input: '{{read_s2_1}}'
  operations : ['subset', 'atmos', 'write']

  read:
    pattern: '*.dim'
    loader: 'snap'
    sort:
      reg_exp: *parse_str_patt
      date_format: *parse_date_patt

  subset:
    epsg: 4326
    bounds: [ 126.0, 38.2, 126.2, 38.0 ]

  atmos:
    config: '$PROJECT_PATH/config/atmos/defaults/S2A_MSI.txt'

  write:
    output_root: '$ETRI_DATA/_sentinel_1_2/export/calibrated/s2/'
    output_prefix: 's2_'
    saver: 'snap'