sort_patt: &sort_patt '([12]\d{3}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])(?:0[0-9]|1[0-9]|2[0-3])(?:[0-5][0-9])(?:[0-5][0-9]))'

load_r:
  input: '/home/airs_khw/mount/d_drive/__develope/temp/etri/etri_data/korea/k3'
  operations: ['read']

  read:
    loader: 'gdal'
    pattern: '*_R.tif'
    sort:
      reg_exp: *sort_patt

load_g:
  input: '/home/airs_khw/mount/d_drive/__develope/temp/etri/etri_data/korea/k3'
  operations: ['read']

  read:
    loader: 'gdal'
    pattern: '*_G.tif'
    sort:
      reg_exp: *sort_patt

load_b:
  input: '/home/airs_khw/mount/d_drive/__develope/temp/etri/etri_data/korea/k3/'
  operations: ['read']

  read:
    loader: 'gdal'
    pattern: '*_B.tif'
    sort:
      func: '!{sort_by_date}'

k3_stack:
  input: ['{{load_r}}', '{{load_g}}', '{{load_b}}']
  operations: ['stack', 'subset']

  stack: # in : list:[FileObjList, ...] -> list:[FileObj, ...]
    axis: -1
  subset:
    bounds: [126.0, 37.0, 127.0, 38.0]

k3_split:
  input: '{{k3_stack}}'
  operations: ['split', 'write']

  split: # in : list:[FileObj, ...] -> list:[FileObjList, ...]
    axis: -1
  write: # in : list:[FileObjList, ...] or list:[FileObj, ...] or FileObj -> same as input
    # output: '$ETRI_DATA/k3_stack.tif'
    output_root: [
      '$ETRI_DATA/korea/K3_r',
      '$ETRI_DATA/korea/K3_g',
      '$ETRI_DATA/korea/K3_b'
    ]
    output_affix: [ '_r', '_g', '_b' ]
#     output_prefix: ['k3_']

k3_prep:
  input: '{{load_r}}'
  operations: ['write']
  write:
    output_root: '$ETRI_DATA/korea/K3_prep'
    output_affix: 'rg_stacked'

k3_stack_2:
  input: [ '{{load_r}}', '{{load_g}}' ]
  operations: [ 'stack', 'write' ]
  stack: # in : list:[FileObjList, ...] -> list:[FileObj, ...]
    axis: -1
  write:
    output_root: '$ETRI_DATA/korea/K3_stacked'
    output_affix: 'rg_stacked'