sort_patt: &parse_str_patt '([12]\d{3}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])T(?:0[0-9]|1[0-9]|2[0-3])(?:[0-5][0-9])(?:[0-5][0-9]))'
date_patt: &parse_date_patt '%Y%m%dT%H%M%S'

read_s2_1:
  input:
    path: '/home/airs_khw/mount/expand/data/etri/_sentinel_1_2/export/source/s2'
    pattern: '*.dim'
    sort:
      reg_exp: *parse_str_patt
      date_format: *parse_date_patt

  operations : ['read']

  read:
    module: 'snap'

read_s2_2:
  input:
    path: '/home/airs_khw/mount/expand/data/etri/_sentinel_1_2/export/source/s2'
    pattern: '*.dim'
    sort:
      func: '!{sort_by_name}'

  operations : ['read']

  read:
    module: 'snap'

read_s2_3:
  input:
    path : '/home/airs_khw/mount/expand/data/etri/_sentinel_1_2/export/source/s2'
    pattern: '*.dim'
    sort:
      func: '!{sort_by_name}'

  operations : ['read']

  read:
    module: 'snap'


cal_1:
  input:
    path : ['{{read_s2_1}}']

  operations : ['atmos']
  atmos:
    config: '/home/airs_khw/__develope/temp/etri/pattern/config/atmos/defaults/S2A_MSI.txt'


cal_2:
  input:
    path : ['{{read_s2_2}}']

  operations : ['atmos']
  atmos:
    config: '/home/airs_khw/__develope/temp/etri/pattern/config/atmos/defaults/S2A_MSI.txt'

cal_3:
  input:
    path : ['{{read_s2_3}}']

  operations : ['atmos']
  atmos:
    config: '/home/airs_khw/__develope/temp/etri/pattern/config/atmos/defaults/S2A_MSI.txt'


subset_1:
  input:
    path: '{{cal_1}}'

  operations : ['subset']

  subset:
    epsg: 4326
    bounds: [ 126.0, 38.2, 126.2, 38.0 ]


stack_1:
  input:
    path : ['{{subset_1}}', '{{cal_2}}', '{{cal_3}}']

  operations : ['stack']

  stack:
    bands: [['B2', 'B3'], ['B4'], ['B5']]

split_1:
  input:
    path : '{{stack_1}}'
  operations : ['split']
  split:
    axis: -1

s_cal_2:
  input:
    path : ['{{split_1}}']

  operations : ['atmos']
  atmos:
    config: '/home/airs_khw/__develope/temp/etri/pattern/config/atmos/defaults/S2A_MSI.txt'

s_cal_3:
  input:
    path : ['{{split_1}}']

  operations : ['atmos']
  atmos:
    config: '/home/airs_khw/__develope/temp/etri/pattern/config/atmos/defaults/S2A_MSI.txt'

subset_2_1:
  input:
    path: '{{s_cal_2}}'

  operations : ['subset']
  subset:
    epsg: 4326
    bounds: [ 126.0, 38.2, 126.2, 38.0 ]

subset_2_2:
  input:
    path: '{{s_cal_3}}'

  operations : ['subset']
  subset:
    epsg: 4326
    bounds: [ 126.0, 38.2, 126.2, 38.0 ]

subset_3:
  input:
    path: '{{subset_2_1}}'
  operations : ['subset']
  subset:
    epsg: 4326
    bounds: [ 126.0, 38.2, 126.2, 38.0 ]

split_2:
  input:
    path : '{{subset_3}}'
  operations : ['split']
  split:
    axis: -1

stack_2:
  input:
    path : ['{{split_2}}', '{{subset_2_2}}']
  operations : ['stack']
  stack:
    axis: -1

write_1:
  input:
    path : '{{stack_2}}'
  operations : ['write']
  write:
    path: [
      '/home/airs_khw/mount/expand/data/etri/_sentinel_1_2/export/source/s2/s2_stack_1',
      '/home/airs_khw/mount/expand/data/etri/_sentinel_1_2/export/source/s2/s2_stack_2'
    ]
    module: 'snap'
    suffix: [ '_1', '_2' ]
    prefix: ['s2_']