sort_patt: &parse_str_patt '([12]\d{3}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\d|3[01])T(?:0[0-9]|1[0-9]|2[0-3])(?:[0-5][0-9])(?:[0-5][0-9]))'
date_patt: &parse_date_patt '%Y%m%dT%H%M%S'

read_s2_1:
  input:
    path: '$ETRI_DATA/_sentinel_1_2/export/source/s2'
    pattern: '*.dim'
    sort:
      reg_exp: *parse_str_patt
      date_format: *parse_date_patt

  operations : ['read']

  read:
    module: 'snap'

read_s2_2:
  input:
    path: '$ETRI_DATA/_sentinel_1_2/export/source/s2'
    pattern: '*.dim'
    sort:
      func: '!{sort_by_name}'

  operations : ['read']

  read:
    module: 'snap'


stack_s2_1_2:
  input:
    path : ['{{read_s2_1}}', '{{read_s2_2}}']

  operations : ['stack']

  stack:
    axis: -1

read_s2_3:
  input:
    path : '$ETRI_DATA/_sentinel_1_2/export/source/s2'
    pattern: '*.dim'
    sort:
      func: '!{sort_by_name}'

  operations : ['read']

  read:
    module: 'snap'

cal_1:
  input:
    path : ['{{read_s2_1}}']

  operations : ['atmos']
  atmos:
    config: '$PROJECT_PATH/config/atmos/defaults/S2A_MSI.txt'

preprocessing_s2_1:
  input:
    path: ['{{stack_s2_1_2}}', '{{cal_1}}', '{{read_s2_3}}']

  operations : ['stack', 'subset']

  stack:
    axis: -1

  subset:
    epsg: 4326
    bounds: [ 126.0, 38.2, 126.2, 38.0 ]

preprocessing_s2_2:
  input:
    path: '{{preprocessing_s2_1}}'

  operations : ['write']

  write:
    path: '$ETRI_DATA/_sentinel_1_2/export/calibrated/s2/'
    prefix: 's2_'
    suffix: ''
    module: 'snap'

preprocessing_s2:
  input:
    path: '{{read_s2_1}}'
    pattern: '*.dim'
    sort:
      reg_exp: *parse_str_patt
      date_format: *parse_date_patt

  operations : ['subset', 'atmos', 'write']

  read:
    module: 'snap'

  subset:
    epsg: 4326
    bounds: [ 126.0, 38.2, 126.2, 38.0 ]

  atmos:
    config: '$PROJECT_PATH/config/atmos/defaults/S2A_MSI.txt'

  write:
    path: '$ETRI_DATA/_sentinel_1_2/export/calibrated/s2/'
    prefix: 's2_'
    suffix: '_cal'
    module: 'snap'