
preprocessing_s1:
  operations : ['read']

  read:
    input: ['/home/airs_khw/mount/expand/data/etri/sentinel_1_2/S1A_IW_GRDH_1SDV_20230519T092327_20230519T092357_048601_05D86A_6D9B.SAFE']
    loader: 'snap'
    bands: ['VV', 'VH']

preprocessing_2:
  operations : ['read']

  read:
    input: '/home/airs_khw/mount/expand/data/etri/sentinel_1_2'
    loader: 'snap'
    bands: ['VV', 'VH']
    ext: '*.SAFE'
