calibrate:
  type: 'dict'
  schema:
    selected_polarisations:
      type: 'list'
      schema:
        type: 'string'
        allowed: ['VV', 'VH', 'HH', 'HV']
    output_sigma_band:
      type: 'boolean'
    output_beta_band:
      type: 'boolean'
    output_gamma_band:
      type: 'boolean'
    output_image_db:
      type: 'boolean'
    output_image_complex:
      type: 'boolean'

