calibrate:
  type: 'dict'
  nullable: true
  schema:
    polarisations:
      type: 'list'
      schema:
        type: 'string'
        allowed: ['VV', 'VH', 'HH', 'HV']
    output_sigma:
      type: 'boolean'
    output_beta:
      type: 'boolean'
    output_gamma:
      type: 'boolean'
    output_in_db:
      type: 'boolean'
    output_in_complex:
      type: 'boolean'

