window_sizes: &window_size_str
  - '5x5'
  - '7x7'
  - '9x9'
  - '11x11'
  - '13x13'
  - '15x15'
  - '17x17'
  - '21x21'

target_windoow_sizes: &target_window_size_str
  - '3x3'
  - '5x5'

speckle_filter:
  type: dict
  schema:
    bands:
      type: 'list'
      schema:
        type: string
    filter:
      type: string
      allowed: ['Refined Lee', 'Boxcar', 'Median', 'Frost', 'Gamma Map', 'Lee', 'IDAN', 'Lee Sigma' ]
    filter_size:
      type: 'list'
      minlength: 2
      maxlength: 2
      schema:
        type: 'integer'
    damping_factor:
      type: 'integer'
    number_looks:
      type: 'integer'
    window_size:
      type: string
      allowed: *window_size_str
    target_window_size:
      type: string
      allowed: *target_window_size_str
    sigma:
      type: 'float'
      allowed: [0.5,0.6,0.7,0.8,0.9]
    an_size:
      type: 'integer'
