speckle_filter:
  type: dict
  schema:
    bands:
      type: 'list'
      schema:
        type: string
    filter:
      type: string
      allowed: ['Refined Lee', 'Boxcar', 'Median', 'Frost', 'Gamma Map', 'Lee', 'IDAN', 'Lee Sigma' ]
    filter_size:
      type: 'list'
      minlength: 2
      maxlength: 2
      schema:
        type: 'integer'
    damping_factor:
      type: 'integer'
    number_looks:
      type: 'integer'
    window_size:
      type: 'integer'
      allowed: [3,5,7,9,11,13,15,17,21]
    target_window_size:
      type: 'integer'
      allowed: [3,5,7,9,11,13,15,17,21]
    sigma:
      type: 'float'
      allowed: [0.5,0.6,0.7,0.8,0.9]
    an_size:
      type: 'integer'
