dem: &dem
  - 'SRTM_3SEC'
  - 'SRTM_1SEC_HGT'
  - 'ACE30'
  - 'GETASSE30'
  - 'COPERNICUS_30'
  - 'COPERNICUS_90'

resample_method: &resample_method
  - 'NEAREST_NEIGHBOR'
  - 'BILINEAR_INTERPOLATION'
  - 'CUBIC_CONVOLUTION'
  - 'BISINC_5_POINT_INTERPOLATION'
  - 'BISINC_11_POINT_INTERPOLATION'
  - 'BISINC_21_POINT_INTERPOLATION'
  - 'BICUBIC_INTERPOLATION'

terrain_correction:
  type: 'dict'
  schema:
    bands:
      type: 'list'
      schema:
        type: 'string'
    dem_name:
      type: 'string'
      allowed: *dem
    pixel_spacing_meter:
      type: 'float'
    pixel_spacing_degree:
      type: 'float'
    dem_method:
      type: 'string'
      allowed: *resample_method
    img_method:
      type: 'string'
      allowed: *resample_method
    save_dem:
      type: 'boolean'
    map_projection:
      type: 'string'